### ISSUE TITLE
Support for HTML5 input elements

### ISSUE THREAD

**Issue by Infinitism** [jescalan/axis#256]
Hey Everyone, 

I thoroughly enjoy Axis and this has greatly improved my workflow and I cannot thank you all for that. I think it would be beneficial if we could extend the functionalities with styling radio and slider to include different input5 types (eg: number), dropdown and checkbox maybe? I think it would help ensure same looks across browser and lots of time usually spent looking those design properties up. 

Thanks!

**Comment by dbox** [comment]
Hey @Infinitism. Agree! 

Here is state of the union on these things currently.

### Dropdown (select)
Ready to go (just needs to be added to axis with tests):
http://codepen.io/dbox/pen/ZGZzmW?editors=110

Demo here (demo is scss but same ideas for stylus):
http://s.codepen.io/dbox/debug/xwNMZd


### Checkboxes

Needs conversion to stylus, a little more testing, and axis tests:
http://codepen.io/dbox/pen/dYBBxb


### Number

No progress.

Happy to accept a PR on any of these, otherwise I will get to it when I can.

Hope this helps a little!

**Comment by Infinitism** [comment]
Hey @dbox thanks for a quick response. I'll try to get on some of those features implemented with Axis and reach out to you guys with a PR soon. 

Thanks for the links:)

**Comment by dbox** [comment]
available in 2.0 (sans number)
